name = "SMPCOBBLE"
author = "Ozoku"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df26983a130ddb6dd881c3e28135136a2a86f8a1048e23825a14a1e520488268"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
