name = "SMPCOBBLE"
author = "Ozoku"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e27bff76aecadfa1152f599f60d23513d05d98ca639d0f971d184df3bae6dc35"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
