name = "SMPCOBBLE"
author = "Ozoku"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc5599a8326ea9c631a39ee6edb14697924becd493c0e36240c5967c3ae68ba7"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
