name = "SMPCOBBLE"
author = "Ozoku"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e5c801b1b6b4cf5c9900a7f87957ee6a77cafc7cd5354a23c39ad9850866cc9"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
