name = "SMPCOBBLE"
author = "Ozoku"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf52fdc162d0b9f042c1159f9d7be3a2a206660912bccfa090213faa4a5286b5"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
