name = "SMPCOBBLE"
author = "Ozoku"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5662bd7b4068ca98175de8ebbcf24b642d5cfeb4f380ce85a5d75339c2becbbf"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
