name = "SMPCOBBLE"
author = "Ozoku"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2cff4c1df2910b7f33d49348bfffaa4a896fb11bd2566e2371f2df6eaddea4c3"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"
